use CaseStudy1;


Select * from Customer;
Select * from prod_cat_info;
Select * from Transactions;


-- Data Prepration

--Total number of rows in each table

 Select Concat(count(customer_ID),' in Customer Table') as [Total rows] from Customer
 Union all
 Select Concat(count(*), ' in prod_cat_info') from prod_cat_info
 Union all
 Select Concat(count(transaction_id), ' in Transactions') from Transactions;

 
-- Total no. of transaction that have a return

Select Count(transaction_id) from Transactions
Where Qty < 0;

-- Date conversion from VARCHAR
Alter Table Transactions Add  T_Date Date
update Transactions
Set T_date = Convert(Date, Tran_Date, 105)


Alter table Customer
Add C_DOB Date
Update Customer
Set C_DOB = Convert(Date, DOB)

--Time range Transaction data is available for analysis

Select Max(T_date) Max_date, Min(T_Date) Min_date, (DATEPART(Day, Max(T_Date)) - DATEPART(Day, Min(T_Date))) as Days,
     (DATEPART(Month, Max(T_Date)) - DATEPART(Month, Min(T_Date))),
      (DATEPART(Year, Max(T_Date)) - DATEPART(Year, Min(T_Date))) as Year
     From Transactions;

--Category where sub category DIY belongs to :
	  Select prod_cat, prod_subcat From prod_cat_info
	   Where prod_subcat ='DIY';

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
	   
Select * from Customer;
Select * from prod_cat_info;
Select * from Transactions;

--Q1- Which channel is mos frequetly used for transactions?

Select TOP 1 Store_type, Count(Store_type) no_of_transactions from Transactions
Group by Store_type
order by Count(Store_type) DESC;
--END

--Q2- What is the count of male and female customers in database?
 Select Gender, Count(Gender) as no_of_customers
 From Customer
 Where Gender is Not Null
  Group by Gender;
  --END

--Q3- For which city do we have the maximum no. of customers and how many?
  Select Top 1 city_code, Count(customer_Id) as no_of_customers
   From Customer
   Group by city_code;
   --END

--Q4- How many sub-categories are there under the Books category?
  Select prod_cat, count(prod_subcat) as no_of_subcat
  From prod_cat_info
  Where prod_cat = 'Books'
  Group by prod_cat;
  --END

--Q5- What is the maximum quantity of the products ever ordered?
  Select Max(Qty) as Maximum_Quantity
  From Transactions;

--Q6- What is the net total revenue generated in categories Electronics and Books?
     Select sum(Cast(total_amt as float)) as [Total Amount]
	 From prod_cat_info P inner Join Transactions T on P.prod_cat_code = T.prod_cat_code and P.prod_sub_cat_code = T.prod_subcat_code
	 Where prod_cat in ('Electronics', 'Books')
	 --End

--Q7- How many customers have greater than 10 transactions excluding returns?
    
Select cust_id, count(transaction_id) as no_of_transactions
From Transactions
Where Qty> 0 
Group by cust_id
Having count(transaction_id)>10
--END
 
--Q8- What is the combined revenue generated from the 'Electronics and 'Clothing' category from 'Flagship stores'?
   Select Store_type, sum(cast(total_amt as float)) as as total_amt_generated
   From Transactions T inner join prod_cat_info P on T.prod_cat_code =P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
   Where prod_cat in ('Electronics', 'Books') And Store_type = 'Flagship store'
   Group by Store_type;
   --END

--Q9- What is the total revenue generated from Male customers in Electronics category? Output should display Total_revenue by prod_subcat.
     Select prod_subcat, sum(cast(total_amt as float)) as total_revenue
	 From Customer inner Join Transactions T on customer_Id = cust_id inner join prod_cat_info p on T.prod_cat_code = P.prod_cat_code And
	 T.prod_subcat_code = P.prod_sub_cat_code
	 Where Gender = 'M' AND prod_cat = 'Electronics'
	 Group by prod_subcat
	 --END

--Q10- What is the percentage of sales and return by product subcategory, display only top 5 subcategory in terms of sales?
        Select Top 5 P.prod_subcat, ((sum(cast(T.total_amt as float)))/(select sum(cast(total_amt as float)) From Transactions) )*100  as percentage_sales_and_Return
		from Transactions t right  join  prod_cat_info P on T.prod_cat_code = P.prod_cat_code and T.prod_subcat_code = P.prod_sub_cat_code
		Group by P.prod_subcat
		order by ((sum(cast(T.total_amt as float)))/(select sum(cast(total_amt as float)) From Transactions) )*100  Desc;
        
--Q11- For all the customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days from max transaction date available in data
    Select customer_id, sum(cast(total_amt as float)) as Total_revenue
	From Customer left Join Transactions on customer_Id = cust_id
	Where (  DATEPART(year, GETDATE())-DATEPART(year, C_DOB) ) Between 25 And 35 and DATEDIFF(day,T_Date, (Select Max(T_Date) from Transactions)) > 30
    Group by customer_Id
  --END

--Q12- Which product category has the maximum value of returns in last 3 month of transactions?
 
  Select Top 1  prod_cat, sum(Cast(Qty as int)) as No_of_returns
  From prod_cat_info p inner join Transactions T on P.prod_cat_code = T.prod_cat_code 
  Where Qty<0 AND DATEDIFF(Month, T_Date, (Select Max(t_date) From Transactions)) <= 3 
  Group by prod_cat
  Order by sum(Cast(Qty as int))
  --END


--Q13 - What store sales the maximum product by value of sale amount by quantity sold?
       Select Top 1 Store_type, Sum(cast(total_amt as float))/Sum(cast(Qty as int)) as SalesBYQtysold
	   From Transactions
	   Group by Store_type
	   Order by Sum(cast(total_amt as float))/Sum(cast(Qty as int)) Desc
	--END

--Q14 - What are the categories for which the average revenue is above Overall average?
       Select prod_cat, Avg(cast(Total_amt as float)) as Avg_revenue
	   From prod_cat_info P inner join Transactions T on P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code =T.prod_subcat_code
	   Group by prod_cat
	   Having Avg(cast(Total_amt as float)) > (Select avg(Cast(Total_amt as float)) from Transactions)
	--END

--Q15 - Find the average and total revenue by each subcategory for the categories which are among the top 5 categories in terms of quantity sold.
     Select prod_subcat, prod_cat, Avg(Cast(total_amt as float)) as Average_amt, Sum(Cast(Total_amt as float)) as Total_amt
	 From prod_cat_info P inner Join Transactions T on P.prod_cat_code = T.prod_cat_code and P.prod_sub_cat_code = T.prod_subcat_code
	 Where P.prod_cat_code in ( select Top 5 prod_cat_code 
	 From Transactions
	 Group by prod_cat_code
	 Order by Sum(Cast(Qty as int)) Desc)
	 Group by prod_subcat, prod_cat
	 Order by prod_cat;
  --END


	











   